version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --config /etc/cloudflared/config.yml --credentials-file /etc/cloudflared/credentials.json twitch-rewards
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml:ro
      - ./cloudflared/credentials.json:/etc/cloudflared/credentials.json:ro
    restart: unless-stopped
    network_mode: host

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  app:
    container_name: twitch-rewards
    image: adai1ne/twitch-rewards:latest
    build: .
    expose:
      - '5151'
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  db:
    container_name: twitch-rewards-db
    image: postgres:16-alpine
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  db:
    driver: local
  caddy_data:
  caddy_config: